version: "3.8"

services:

  sias:
    image: "bitnami/java:14"
    container_name: sias
    working_dir: /app
    command: "java -jar sias-0.0.1-SNAPSHOT.jar"
    volumes:
      - ./target:/app

  mongo:
    image: "bitnami/mongodb:4.4"
    user: root
    container_name: mongo
    volumes:
      - ./var/mongo:/bitnami/mongodb
    ports:
      - 38128:27017