version: "3.8"

services:

  sias:
    build:
      context: ./
      dockerfile: docker/sias/Dockerfile
    container_name: sias
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 6543:5342
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sias

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: admin